// Code generated by protoc-gen-go.
// source: api.proto
// DO NOT EDIT!

/*
Package api is a generated protocol buffer package.

It is generated from these files:
	api.proto

It has these top-level messages:
	GunMessage
	AddDelegationMessage
	AddDelegationRoleAndKeysMessage
	AddDelegationPathsMessage
	RemoveDelegationKeysAndPathsMessage
	RemoveDelegationRoleMessage
	RemoveDelegationPathsMessage
	RemoveDelegationKeysMessage
	RoleNameMessage
	RotateKeyMessage
	InitMessage
	RoleNameList
	RoleNameListMessage
	RoleNameListResponse
	TargetNameMessage
	Target
	TargetWithRole
	TargetWithRoleResponse
	TargetWithRoleNameList
	TargetWithRoleNameListResponse
	TargetByNameAction
	Signature
	PublicKey
	PublicKeyResponse
	DelegationRole
	TargetSigned
	TargetSignedList
	TargetSignedListResponse
	BasicResponse
	Change
	ChangeList
	ChangeListResponse
	RootRole
	Role
	RoleList
	RoleListResponse
	RoleWithSignatures
	RoleWithSignaturesList
	RoleWithSignaturesListResponse
	CryptoServiceMessage
	CryptoServiceCreateMessage
	Signer
	PrivateKey
	CryptoServiceAddKeyMessage
	PrivateKeyResponse
	KeyIDMessage
	KeyIDsListResponse
	SigningKeyIDsToRolesResponse
	VersionMessage
*/
package api

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import google_protobuf "github.com/golang/protobuf/ptypes/empty"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type GunMessage struct {
	Gun string `protobuf:"bytes,1,opt,name=gun" json:"gun,omitempty"`
}

func (m *GunMessage) Reset()                    { *m = GunMessage{} }
func (m *GunMessage) String() string            { return proto.CompactTextString(m) }
func (*GunMessage) ProtoMessage()               {}
func (*GunMessage) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *GunMessage) GetGun() string {
	if m != nil {
		return m.Gun
	}
	return ""
}

type AddDelegationMessage struct {
	Name           string       `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	DelegationKeys []*PublicKey `protobuf:"bytes,2,rep,name=delegationKeys" json:"delegationKeys,omitempty"`
	Paths          []string     `protobuf:"bytes,3,rep,name=paths" json:"paths,omitempty"`
	Gun            string       `protobuf:"bytes,4,opt,name=gun" json:"gun,omitempty"`
}

func (m *AddDelegationMessage) Reset()                    { *m = AddDelegationMessage{} }
func (m *AddDelegationMessage) String() string            { return proto.CompactTextString(m) }
func (*AddDelegationMessage) ProtoMessage()               {}
func (*AddDelegationMessage) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *AddDelegationMessage) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *AddDelegationMessage) GetDelegationKeys() []*PublicKey {
	if m != nil {
		return m.DelegationKeys
	}
	return nil
}

func (m *AddDelegationMessage) GetPaths() []string {
	if m != nil {
		return m.Paths
	}
	return nil
}

func (m *AddDelegationMessage) GetGun() string {
	if m != nil {
		return m.Gun
	}
	return ""
}

type AddDelegationRoleAndKeysMessage struct {
	Name           string       `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	DelegationKeys []*PublicKey `protobuf:"bytes,2,rep,name=delegationKeys" json:"delegationKeys,omitempty"`
	Gun            string       `protobuf:"bytes,3,opt,name=gun" json:"gun,omitempty"`
}

func (m *AddDelegationRoleAndKeysMessage) Reset()                    { *m = AddDelegationRoleAndKeysMessage{} }
func (m *AddDelegationRoleAndKeysMessage) String() string            { return proto.CompactTextString(m) }
func (*AddDelegationRoleAndKeysMessage) ProtoMessage()               {}
func (*AddDelegationRoleAndKeysMessage) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *AddDelegationRoleAndKeysMessage) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *AddDelegationRoleAndKeysMessage) GetDelegationKeys() []*PublicKey {
	if m != nil {
		return m.DelegationKeys
	}
	return nil
}

func (m *AddDelegationRoleAndKeysMessage) GetGun() string {
	if m != nil {
		return m.Gun
	}
	return ""
}

type AddDelegationPathsMessage struct {
	Name  string   `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Paths []string `protobuf:"bytes,2,rep,name=paths" json:"paths,omitempty"`
	Gun   string   `protobuf:"bytes,3,opt,name=gun" json:"gun,omitempty"`
}

func (m *AddDelegationPathsMessage) Reset()                    { *m = AddDelegationPathsMessage{} }
func (m *AddDelegationPathsMessage) String() string            { return proto.CompactTextString(m) }
func (*AddDelegationPathsMessage) ProtoMessage()               {}
func (*AddDelegationPathsMessage) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *AddDelegationPathsMessage) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *AddDelegationPathsMessage) GetPaths() []string {
	if m != nil {
		return m.Paths
	}
	return nil
}

func (m *AddDelegationPathsMessage) GetGun() string {
	if m != nil {
		return m.Gun
	}
	return ""
}

type RemoveDelegationKeysAndPathsMessage struct {
	Name   string   `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	KeyIDs []string `protobuf:"bytes,2,rep,name=keyIDs" json:"keyIDs,omitempty"`
	Paths  []string `protobuf:"bytes,3,rep,name=paths" json:"paths,omitempty"`
	Gun    string   `protobuf:"bytes,4,opt,name=gun" json:"gun,omitempty"`
}

func (m *RemoveDelegationKeysAndPathsMessage) Reset()         { *m = RemoveDelegationKeysAndPathsMessage{} }
func (m *RemoveDelegationKeysAndPathsMessage) String() string { return proto.CompactTextString(m) }
func (*RemoveDelegationKeysAndPathsMessage) ProtoMessage()    {}
func (*RemoveDelegationKeysAndPathsMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor0, []int{4}
}

func (m *RemoveDelegationKeysAndPathsMessage) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *RemoveDelegationKeysAndPathsMessage) GetKeyIDs() []string {
	if m != nil {
		return m.KeyIDs
	}
	return nil
}

func (m *RemoveDelegationKeysAndPathsMessage) GetPaths() []string {
	if m != nil {
		return m.Paths
	}
	return nil
}

func (m *RemoveDelegationKeysAndPathsMessage) GetGun() string {
	if m != nil {
		return m.Gun
	}
	return ""
}

type RemoveDelegationRoleMessage struct {
	Name string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Gun  string `protobuf:"bytes,2,opt,name=gun" json:"gun,omitempty"`
}

func (m *RemoveDelegationRoleMessage) Reset()                    { *m = RemoveDelegationRoleMessage{} }
func (m *RemoveDelegationRoleMessage) String() string            { return proto.CompactTextString(m) }
func (*RemoveDelegationRoleMessage) ProtoMessage()               {}
func (*RemoveDelegationRoleMessage) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *RemoveDelegationRoleMessage) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *RemoveDelegationRoleMessage) GetGun() string {
	if m != nil {
		return m.Gun
	}
	return ""
}

type RemoveDelegationPathsMessage struct {
	Name  string   `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Paths []string `protobuf:"bytes,2,rep,name=paths" json:"paths,omitempty"`
	Gun   string   `protobuf:"bytes,3,opt,name=gun" json:"gun,omitempty"`
}

func (m *RemoveDelegationPathsMessage) Reset()                    { *m = RemoveDelegationPathsMessage{} }
func (m *RemoveDelegationPathsMessage) String() string            { return proto.CompactTextString(m) }
func (*RemoveDelegationPathsMessage) ProtoMessage()               {}
func (*RemoveDelegationPathsMessage) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *RemoveDelegationPathsMessage) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *RemoveDelegationPathsMessage) GetPaths() []string {
	if m != nil {
		return m.Paths
	}
	return nil
}

func (m *RemoveDelegationPathsMessage) GetGun() string {
	if m != nil {
		return m.Gun
	}
	return ""
}

type RemoveDelegationKeysMessage struct {
	Name   string   `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	KeyIDs []string `protobuf:"bytes,2,rep,name=keyIDs" json:"keyIDs,omitempty"`
	Gun    string   `protobuf:"bytes,3,opt,name=gun" json:"gun,omitempty"`
}

func (m *RemoveDelegationKeysMessage) Reset()                    { *m = RemoveDelegationKeysMessage{} }
func (m *RemoveDelegationKeysMessage) String() string            { return proto.CompactTextString(m) }
func (*RemoveDelegationKeysMessage) ProtoMessage()               {}
func (*RemoveDelegationKeysMessage) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *RemoveDelegationKeysMessage) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *RemoveDelegationKeysMessage) GetKeyIDs() []string {
	if m != nil {
		return m.KeyIDs
	}
	return nil
}

func (m *RemoveDelegationKeysMessage) GetGun() string {
	if m != nil {
		return m.Gun
	}
	return ""
}

type RoleNameMessage struct {
	Role string `protobuf:"bytes,1,opt,name=role" json:"role,omitempty"`
	Gun  string `protobuf:"bytes,2,opt,name=gun" json:"gun,omitempty"`
}

func (m *RoleNameMessage) Reset()                    { *m = RoleNameMessage{} }
func (m *RoleNameMessage) String() string            { return proto.CompactTextString(m) }
func (*RoleNameMessage) ProtoMessage()               {}
func (*RoleNameMessage) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

func (m *RoleNameMessage) GetRole() string {
	if m != nil {
		return m.Role
	}
	return ""
}

func (m *RoleNameMessage) GetGun() string {
	if m != nil {
		return m.Gun
	}
	return ""
}

type RotateKeyMessage struct {
	Role             string   `protobuf:"bytes,1,opt,name=role" json:"role,omitempty"`
	ServerManagesKey bool     `protobuf:"varint,2,opt,name=serverManagesKey" json:"serverManagesKey,omitempty"`
	KeyList          []string `protobuf:"bytes,3,rep,name=keyList" json:"keyList,omitempty"`
	Gun              string   `protobuf:"bytes,4,opt,name=gun" json:"gun,omitempty"`
}

func (m *RotateKeyMessage) Reset()                    { *m = RotateKeyMessage{} }
func (m *RotateKeyMessage) String() string            { return proto.CompactTextString(m) }
func (*RotateKeyMessage) ProtoMessage()               {}
func (*RotateKeyMessage) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{9} }

func (m *RotateKeyMessage) GetRole() string {
	if m != nil {
		return m.Role
	}
	return ""
}

func (m *RotateKeyMessage) GetServerManagesKey() bool {
	if m != nil {
		return m.ServerManagesKey
	}
	return false
}

func (m *RotateKeyMessage) GetKeyList() []string {
	if m != nil {
		return m.KeyList
	}
	return nil
}

func (m *RotateKeyMessage) GetGun() string {
	if m != nil {
		return m.Gun
	}
	return ""
}

// InitMessage holds a list of root key IDs and a list of roles for which
// the server automatically should manage the keys
type InitMessage struct {
	RootKeyIDs         []string      `protobuf:"bytes,1,rep,name=rootKeyIDs" json:"rootKeyIDs,omitempty"`
	ServerManagedRoles *RoleNameList `protobuf:"bytes,2,opt,name=serverManagedRoles" json:"serverManagedRoles,omitempty"`
	Gun                string        `protobuf:"bytes,3,opt,name=gun" json:"gun,omitempty"`
}

func (m *InitMessage) Reset()                    { *m = InitMessage{} }
func (m *InitMessage) String() string            { return proto.CompactTextString(m) }
func (*InitMessage) ProtoMessage()               {}
func (*InitMessage) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{10} }

func (m *InitMessage) GetRootKeyIDs() []string {
	if m != nil {
		return m.RootKeyIDs
	}
	return nil
}

func (m *InitMessage) GetServerManagedRoles() *RoleNameList {
	if m != nil {
		return m.ServerManagedRoles
	}
	return nil
}

func (m *InitMessage) GetGun() string {
	if m != nil {
		return m.Gun
	}
	return ""
}

// RoleNameList message holds a list of TUF role names
type RoleNameList struct {
	Roles []string `protobuf:"bytes,1,rep,name=roles" json:"roles,omitempty"`
}

func (m *RoleNameList) Reset()                    { *m = RoleNameList{} }
func (m *RoleNameList) String() string            { return proto.CompactTextString(m) }
func (*RoleNameList) ProtoMessage()               {}
func (*RoleNameList) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{11} }

func (m *RoleNameList) GetRoles() []string {
	if m != nil {
		return m.Roles
	}
	return nil
}

type RoleNameListMessage struct {
	Roles []string `protobuf:"bytes,1,rep,name=roles" json:"roles,omitempty"`
	Gun   string   `protobuf:"bytes,2,opt,name=gun" json:"gun,omitempty"`
}

func (m *RoleNameListMessage) Reset()                    { *m = RoleNameListMessage{} }
func (m *RoleNameListMessage) String() string            { return proto.CompactTextString(m) }
func (*RoleNameListMessage) ProtoMessage()               {}
func (*RoleNameListMessage) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{12} }

func (m *RoleNameListMessage) GetRoles() []string {
	if m != nil {
		return m.Roles
	}
	return nil
}

func (m *RoleNameListMessage) GetGun() string {
	if m != nil {
		return m.Gun
	}
	return ""
}

type RoleNameListResponse struct {
	RoleNameList *RoleNameList `protobuf:"bytes,1,opt,name=roleNameList" json:"roleNameList,omitempty"`
	Success      bool          `protobuf:"varint,2,opt,name=success" json:"success,omitempty"`
	Message      string        `protobuf:"bytes,3,opt,name=message" json:"message,omitempty"`
}

func (m *RoleNameListResponse) Reset()                    { *m = RoleNameListResponse{} }
func (m *RoleNameListResponse) String() string            { return proto.CompactTextString(m) }
func (*RoleNameListResponse) ProtoMessage()               {}
func (*RoleNameListResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{13} }

func (m *RoleNameListResponse) GetRoleNameList() *RoleNameList {
	if m != nil {
		return m.RoleNameList
	}
	return nil
}

func (m *RoleNameListResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *RoleNameListResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type TargetNameMessage struct {
	Name string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Gun  string `protobuf:"bytes,2,opt,name=gun" json:"gun,omitempty"`
}

func (m *TargetNameMessage) Reset()                    { *m = TargetNameMessage{} }
func (m *TargetNameMessage) String() string            { return proto.CompactTextString(m) }
func (*TargetNameMessage) ProtoMessage()               {}
func (*TargetNameMessage) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{14} }

func (m *TargetNameMessage) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *TargetNameMessage) GetGun() string {
	if m != nil {
		return m.Gun
	}
	return ""
}

// Target message describes a TUF target
type Target struct {
	Gun    string            `protobuf:"bytes,1,opt,name=gun" json:"gun,omitempty"`
	Name   string            `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	Length int64             `protobuf:"varint,3,opt,name=length" json:"length,omitempty"`
	Hashes map[string][]byte `protobuf:"bytes,4,rep,name=hashes" json:"hashes,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value,proto3"`
}

func (m *Target) Reset()                    { *m = Target{} }
func (m *Target) String() string            { return proto.CompactTextString(m) }
func (*Target) ProtoMessage()               {}
func (*Target) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{15} }

func (m *Target) GetGun() string {
	if m != nil {
		return m.Gun
	}
	return ""
}

func (m *Target) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Target) GetLength() int64 {
	if m != nil {
		return m.Length
	}
	return 0
}

func (m *Target) GetHashes() map[string][]byte {
	if m != nil {
		return m.Hashes
	}
	return nil
}

// TargetWithRole represents a Target that exists in a particular role
type TargetWithRole struct {
	Target *Target `protobuf:"bytes,1,opt,name=target" json:"target,omitempty"`
	Role   string  `protobuf:"bytes,2,opt,name=role" json:"role,omitempty"`
}

func (m *TargetWithRole) Reset()                    { *m = TargetWithRole{} }
func (m *TargetWithRole) String() string            { return proto.CompactTextString(m) }
func (*TargetWithRole) ProtoMessage()               {}
func (*TargetWithRole) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{16} }

func (m *TargetWithRole) GetTarget() *Target {
	if m != nil {
		return m.Target
	}
	return nil
}

func (m *TargetWithRole) GetRole() string {
	if m != nil {
		return m.Role
	}
	return ""
}

type TargetWithRoleResponse struct {
	TargetWithRole *TargetWithRole `protobuf:"bytes,1,opt,name=targetWithRole" json:"targetWithRole,omitempty"`
	Success        bool            `protobuf:"varint,2,opt,name=success" json:"success,omitempty"`
	Message        string          `protobuf:"bytes,3,opt,name=message" json:"message,omitempty"`
}

func (m *TargetWithRoleResponse) Reset()                    { *m = TargetWithRoleResponse{} }
func (m *TargetWithRoleResponse) String() string            { return proto.CompactTextString(m) }
func (*TargetWithRoleResponse) ProtoMessage()               {}
func (*TargetWithRoleResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{17} }

func (m *TargetWithRoleResponse) GetTargetWithRole() *TargetWithRole {
	if m != nil {
		return m.TargetWithRole
	}
	return nil
}

func (m *TargetWithRoleResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *TargetWithRoleResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type TargetWithRoleNameList struct {
	Targets []*TargetWithRole `protobuf:"bytes,1,rep,name=targets" json:"targets,omitempty"`
}

func (m *TargetWithRoleNameList) Reset()                    { *m = TargetWithRoleNameList{} }
func (m *TargetWithRoleNameList) String() string            { return proto.CompactTextString(m) }
func (*TargetWithRoleNameList) ProtoMessage()               {}
func (*TargetWithRoleNameList) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{18} }

func (m *TargetWithRoleNameList) GetTargets() []*TargetWithRole {
	if m != nil {
		return m.Targets
	}
	return nil
}

type TargetWithRoleNameListResponse struct {
	TargetWithRoleNameList *TargetWithRoleNameList `protobuf:"bytes,1,opt,name=targetWithRoleNameList" json:"targetWithRoleNameList,omitempty"`
	Success                bool                    `protobuf:"varint,2,opt,name=success" json:"success,omitempty"`
}

func (m *TargetWithRoleNameListResponse) Reset()                    { *m = TargetWithRoleNameListResponse{} }
func (m *TargetWithRoleNameListResponse) String() string            { return proto.CompactTextString(m) }
func (*TargetWithRoleNameListResponse) ProtoMessage()               {}
func (*TargetWithRoleNameListResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{19} }

func (m *TargetWithRoleNameListResponse) GetTargetWithRoleNameList() *TargetWithRoleNameList {
	if m != nil {
		return m.TargetWithRoleNameList
	}
	return nil
}

func (m *TargetWithRoleNameListResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

type TargetByNameAction struct {
	Name  string        `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Roles *RoleNameList `protobuf:"bytes,2,opt,name=roles" json:"roles,omitempty"`
	Gun   string        `protobuf:"bytes,3,opt,name=gun" json:"gun,omitempty"`
}

func (m *TargetByNameAction) Reset()                    { *m = TargetByNameAction{} }
func (m *TargetByNameAction) String() string            { return proto.CompactTextString(m) }
func (*TargetByNameAction) ProtoMessage()               {}
func (*TargetByNameAction) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{20} }

func (m *TargetByNameAction) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *TargetByNameAction) GetRoles() *RoleNameList {
	if m != nil {
		return m.Roles
	}
	return nil
}

func (m *TargetByNameAction) GetGun() string {
	if m != nil {
		return m.Gun
	}
	return ""
}

type Signature struct {
	KeyID     string `protobuf:"bytes,1,opt,name=keyID" json:"keyID,omitempty"`
	Method    string `protobuf:"bytes,2,opt,name=method" json:"method,omitempty"`
	Signature []byte `protobuf:"bytes,3,opt,name=signature,proto3" json:"signature,omitempty"`
	IsValid   bool   `protobuf:"varint,4,opt,name=isValid" json:"isValid,omitempty"`
}

func (m *Signature) Reset()                    { *m = Signature{} }
func (m *Signature) String() string            { return proto.CompactTextString(m) }
func (*Signature) ProtoMessage()               {}
func (*Signature) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{21} }

func (m *Signature) GetKeyID() string {
	if m != nil {
		return m.KeyID
	}
	return ""
}

func (m *Signature) GetMethod() string {
	if m != nil {
		return m.Method
	}
	return ""
}

func (m *Signature) GetSignature() []byte {
	if m != nil {
		return m.Signature
	}
	return nil
}

func (m *Signature) GetIsValid() bool {
	if m != nil {
		return m.IsValid
	}
	return false
}

type PublicKey struct {
	Id        string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Algorithm string `protobuf:"bytes,2,opt,name=algorithm" json:"algorithm,omitempty"`
	Public    []byte `protobuf:"bytes,3,opt,name=public,proto3" json:"public,omitempty"`
}

func (m *PublicKey) Reset()                    { *m = PublicKey{} }
func (m *PublicKey) String() string            { return proto.CompactTextString(m) }
func (*PublicKey) ProtoMessage()               {}
func (*PublicKey) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{22} }

func (m *PublicKey) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *PublicKey) GetAlgorithm() string {
	if m != nil {
		return m.Algorithm
	}
	return ""
}

func (m *PublicKey) GetPublic() []byte {
	if m != nil {
		return m.Public
	}
	return nil
}

type PublicKeyResponse struct {
	Pubkey  *PublicKey `protobuf:"bytes,1,opt,name=pubkey" json:"pubkey,omitempty"`
	Success bool       `protobuf:"varint,2,opt,name=success" json:"success,omitempty"`
}

func (m *PublicKeyResponse) Reset()                    { *m = PublicKeyResponse{} }
func (m *PublicKeyResponse) String() string            { return proto.CompactTextString(m) }
func (*PublicKeyResponse) ProtoMessage()               {}
func (*PublicKeyResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{23} }

func (m *PublicKeyResponse) GetPubkey() *PublicKey {
	if m != nil {
		return m.Pubkey
	}
	return nil
}

func (m *PublicKeyResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

type DelegationRole struct {
	Keys      map[string]*PublicKey `protobuf:"bytes,1,rep,name=keys" json:"keys,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Name      string                `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	Threshold int32                 `protobuf:"varint,3,opt,name=threshold" json:"threshold,omitempty"`
	Paths     []string              `protobuf:"bytes,4,rep,name=paths" json:"paths,omitempty"`
}

func (m *DelegationRole) Reset()                    { *m = DelegationRole{} }
func (m *DelegationRole) String() string            { return proto.CompactTextString(m) }
func (*DelegationRole) ProtoMessage()               {}
func (*DelegationRole) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{24} }

func (m *DelegationRole) GetKeys() map[string]*PublicKey {
	if m != nil {
		return m.Keys
	}
	return nil
}

func (m *DelegationRole) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *DelegationRole) GetThreshold() int32 {
	if m != nil {
		return m.Threshold
	}
	return 0
}

func (m *DelegationRole) GetPaths() []string {
	if m != nil {
		return m.Paths
	}
	return nil
}

type TargetSigned struct {
	Role       *DelegationRole `protobuf:"bytes,1,opt,name=role" json:"role,omitempty"`
	Target     *Target         `protobuf:"bytes,2,opt,name=target" json:"target,omitempty"`
	Signatures []*Signature    `protobuf:"bytes,3,rep,name=signatures" json:"signatures,omitempty"`
}

func (m *TargetSigned) Reset()                    { *m = TargetSigned{} }
func (m *TargetSigned) String() string            { return proto.CompactTextString(m) }
func (*TargetSigned) ProtoMessage()               {}
func (*TargetSigned) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{25} }

func (m *TargetSigned) GetRole() *DelegationRole {
	if m != nil {
		return m.Role
	}
	return nil
}

func (m *TargetSigned) GetTarget() *Target {
	if m != nil {
		return m.Target
	}
	return nil
}

func (m *TargetSigned) GetSignatures() []*Signature {
	if m != nil {
		return m.Signatures
	}
	return nil
}

type TargetSignedList struct {
	Targets []*TargetSigned `protobuf:"bytes,1,rep,name=targets" json:"targets,omitempty"`
}

func (m *TargetSignedList) Reset()                    { *m = TargetSignedList{} }
func (m *TargetSignedList) String() string            { return proto.CompactTextString(m) }
func (*TargetSignedList) ProtoMessage()               {}
func (*TargetSignedList) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{26} }

func (m *TargetSignedList) GetTargets() []*TargetSigned {
	if m != nil {
		return m.Targets
	}
	return nil
}

type TargetSignedListResponse struct {
	TargetSignedList *TargetSignedList `protobuf:"bytes,1,opt,name=targetSignedList" json:"targetSignedList,omitempty"`
	Success          bool              `protobuf:"varint,2,opt,name=success" json:"success,omitempty"`
	Message          string            `protobuf:"bytes,3,opt,name=message" json:"message,omitempty"`
}

func (m *TargetSignedListResponse) Reset()                    { *m = TargetSignedListResponse{} }
func (m *TargetSignedListResponse) String() string            { return proto.CompactTextString(m) }
func (*TargetSignedListResponse) ProtoMessage()               {}
func (*TargetSignedListResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{27} }

func (m *TargetSignedListResponse) GetTargetSignedList() *TargetSignedList {
	if m != nil {
		return m.TargetSignedList
	}
	return nil
}

func (m *TargetSignedListResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *TargetSignedListResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

// BasicResponse describes a response with a true/false success indicator,
// and if false, an error type and message. See the errors.go file in this
// package for the possible errors and a translation function between the
// BasicResponse object and a concrete error type.
type BasicResponse struct {
	Success bool   `protobuf:"varint,1,opt,name=success" json:"success,omitempty"`
	Message string `protobuf:"bytes,2,opt,name=message" json:"message,omitempty"`
}

func (m *BasicResponse) Reset()                    { *m = BasicResponse{} }
func (m *BasicResponse) String() string            { return proto.CompactTextString(m) }
func (*BasicResponse) ProtoMessage()               {}
func (*BasicResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{28} }

func (m *BasicResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *BasicResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

// Change describes a repository's change
type Change struct {
	Action  string `protobuf:"bytes,1,opt,name=action" json:"action,omitempty"`
	Scope   string `protobuf:"bytes,2,opt,name=scope" json:"scope,omitempty"`
	Type    string `protobuf:"bytes,3,opt,name=type" json:"type,omitempty"`
	Path    string `protobuf:"bytes,4,opt,name=path" json:"path,omitempty"`
	Content []byte `protobuf:"bytes,5,opt,name=content,proto3" json:"content,omitempty"`
}

func (m *Change) Reset()                    { *m = Change{} }
func (m *Change) String() string            { return proto.CompactTextString(m) }
func (*Change) ProtoMessage()               {}
func (*Change) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{29} }

func (m *Change) GetAction() string {
	if m != nil {
		return m.Action
	}
	return ""
}

func (m *Change) GetScope() string {
	if m != nil {
		return m.Scope
	}
	return ""
}

func (m *Change) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *Change) GetPath() string {
	if m != nil {
		return m.Path
	}
	return ""
}

func (m *Change) GetContent() []byte {
	if m != nil {
		return m.Content
	}
	return nil
}

// ChangeList describes a list of a repository's changes
type ChangeList struct {
	Changes []*Change `protobuf:"bytes,1,rep,name=changes" json:"changes,omitempty"`
}

func (m *ChangeList) Reset()                    { *m = ChangeList{} }
func (m *ChangeList) String() string            { return proto.CompactTextString(m) }
func (*ChangeList) ProtoMessage()               {}
func (*ChangeList) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{30} }

func (m *ChangeList) GetChanges() []*Change {
	if m != nil {
		return m.Changes
	}
	return nil
}

type ChangeListResponse struct {
	Changelist *ChangeList `protobuf:"bytes,1,opt,name=changelist" json:"changelist,omitempty"`
	Success    bool        `protobuf:"varint,2,opt,name=success" json:"success,omitempty"`
	Message    string      `protobuf:"bytes,3,opt,name=message" json:"message,omitempty"`
}

func (m *ChangeListResponse) Reset()                    { *m = ChangeListResponse{} }
func (m *ChangeListResponse) String() string            { return proto.CompactTextString(m) }
func (*ChangeListResponse) ProtoMessage()               {}
func (*ChangeListResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{31} }

func (m *ChangeListResponse) GetChangelist() *ChangeList {
	if m != nil {
		return m.Changelist
	}
	return nil
}

func (m *ChangeListResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *ChangeListResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type RootRole struct {
	KeyIDs    []string `protobuf:"bytes,1,rep,name=keyIDs" json:"keyIDs,omitempty"`
	Threshold int32    `protobuf:"varint,2,opt,name=threshold" json:"threshold,omitempty"`
}

func (m *RootRole) Reset()                    { *m = RootRole{} }
func (m *RootRole) String() string            { return proto.CompactTextString(m) }
func (*RootRole) ProtoMessage()               {}
func (*RootRole) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{32} }

func (m *RootRole) GetKeyIDs() []string {
	if m != nil {
		return m.KeyIDs
	}
	return nil
}

func (m *RootRole) GetThreshold() int32 {
	if m != nil {
		return m.Threshold
	}
	return 0
}

type Role struct {
	RootRole *RootRole `protobuf:"bytes,1,opt,name=rootRole" json:"rootRole,omitempty"`
	Name     string    `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	Paths    []string  `protobuf:"bytes,3,rep,name=paths" json:"paths,omitempty"`
}

func (m *Role) Reset()                    { *m = Role{} }
func (m *Role) String() string            { return proto.CompactTextString(m) }
func (*Role) ProtoMessage()               {}
func (*Role) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{33} }

func (m *Role) GetRootRole() *RootRole {
	if m != nil {
		return m.RootRole
	}
	return nil
}

func (m *Role) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Role) GetPaths() []string {
	if m != nil {
		return m.Paths
	}
	return nil
}

type RoleList struct {
	Roles []*Role `protobuf:"bytes,1,rep,name=roles" json:"roles,omitempty"`
}

func (m *RoleList) Reset()                    { *m = RoleList{} }
func (m *RoleList) String() string            { return proto.CompactTextString(m) }
func (*RoleList) ProtoMessage()               {}
func (*RoleList) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{34} }

func (m *RoleList) GetRoles() []*Role {
	if m != nil {
		return m.Roles
	}
	return nil
}

type RoleListResponse struct {
	RoleList *RoleList `protobuf:"bytes,1,opt,name=roleList" json:"roleList,omitempty"`
	Success  bool      `protobuf:"varint,2,opt,name=success" json:"success,omitempty"`
	Message  string    `protobuf:"bytes,3,opt,name=message" json:"message,omitempty"`
}

func (m *RoleListResponse) Reset()                    { *m = RoleListResponse{} }
func (m *RoleListResponse) String() string            { return proto.CompactTextString(m) }
func (*RoleListResponse) ProtoMessage()               {}
func (*RoleListResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{35} }

func (m *RoleListResponse) GetRoleList() *RoleList {
	if m != nil {
		return m.RoleList
	}
	return nil
}

func (m *RoleListResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *RoleListResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type RoleWithSignatures struct {
	Signatures []*Signature `protobuf:"bytes,1,rep,name=signatures" json:"signatures,omitempty"`
	Role       *Role        `protobuf:"bytes,2,opt,name=role" json:"role,omitempty"`
}

func (m *RoleWithSignatures) Reset()                    { *m = RoleWithSignatures{} }
func (m *RoleWithSignatures) String() string            { return proto.CompactTextString(m) }
func (*RoleWithSignatures) ProtoMessage()               {}
func (*RoleWithSignatures) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{36} }

func (m *RoleWithSignatures) GetSignatures() []*Signature {
	if m != nil {
		return m.Signatures
	}
	return nil
}

func (m *RoleWithSignatures) GetRole() *Role {
	if m != nil {
		return m.Role
	}
	return nil
}

type RoleWithSignaturesList struct {
	RoleWithSignatures []*RoleWithSignatures `protobuf:"bytes,1,rep,name=roleWithSignatures" json:"roleWithSignatures,omitempty"`
}

func (m *RoleWithSignaturesList) Reset()                    { *m = RoleWithSignaturesList{} }
func (m *RoleWithSignaturesList) String() string            { return proto.CompactTextString(m) }
func (*RoleWithSignaturesList) ProtoMessage()               {}
func (*RoleWithSignaturesList) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{37} }

func (m *RoleWithSignaturesList) GetRoleWithSignatures() []*RoleWithSignatures {
	if m != nil {
		return m.RoleWithSignatures
	}
	return nil
}

type RoleWithSignaturesListResponse struct {
	RoleWithSignaturesList *RoleWithSignaturesList `protobuf:"bytes,1,opt,name=roleWithSignaturesList" json:"roleWithSignaturesList,omitempty"`
	Success                bool                    `protobuf:"varint,2,opt,name=success" json:"success,omitempty"`
	Message                string                  `protobuf:"bytes,3,opt,name=message" json:"message,omitempty"`
}

func (m *RoleWithSignaturesListResponse) Reset()                    { *m = RoleWithSignaturesListResponse{} }
func (m *RoleWithSignaturesListResponse) String() string            { return proto.CompactTextString(m) }
func (*RoleWithSignaturesListResponse) ProtoMessage()               {}
func (*RoleWithSignaturesListResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{38} }

func (m *RoleWithSignaturesListResponse) GetRoleWithSignaturesList() *RoleWithSignaturesList {
	if m != nil {
		return m.RoleWithSignaturesList
	}
	return nil
}

func (m *RoleWithSignaturesListResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *RoleWithSignaturesListResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

// FIXME: unimplemented
type CryptoServiceMessage struct {
}

func (m *CryptoServiceMessage) Reset()                    { *m = CryptoServiceMessage{} }
func (m *CryptoServiceMessage) String() string            { return proto.CompactTextString(m) }
func (*CryptoServiceMessage) ProtoMessage()               {}
func (*CryptoServiceMessage) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{39} }

type CryptoServiceCreateMessage struct {
	RoleName  string `protobuf:"bytes,1,opt,name=roleName" json:"roleName,omitempty"`
	Gun       string `protobuf:"bytes,2,opt,name=gun" json:"gun,omitempty"`
	Algorithm string `protobuf:"bytes,3,opt,name=algorithm" json:"algorithm,omitempty"`
}

func (m *CryptoServiceCreateMessage) Reset()                    { *m = CryptoServiceCreateMessage{} }
func (m *CryptoServiceCreateMessage) String() string            { return proto.CompactTextString(m) }
func (*CryptoServiceCreateMessage) ProtoMessage()               {}
func (*CryptoServiceCreateMessage) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{40} }

func (m *CryptoServiceCreateMessage) GetRoleName() string {
	if m != nil {
		return m.RoleName
	}
	return ""
}

func (m *CryptoServiceCreateMessage) GetGun() string {
	if m != nil {
		return m.Gun
	}
	return ""
}

func (m *CryptoServiceCreateMessage) GetAlgorithm() string {
	if m != nil {
		return m.Algorithm
	}
	return ""
}

type Signer struct {
	Pubkey    *PublicKey `protobuf:"bytes,1,opt,name=pubkey" json:"pubkey,omitempty"`
	Signature string     `protobuf:"bytes,2,opt,name=signature" json:"signature,omitempty"`
}

func (m *Signer) Reset()                    { *m = Signer{} }
func (m *Signer) String() string            { return proto.CompactTextString(m) }
func (*Signer) ProtoMessage()               {}
func (*Signer) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{41} }

func (m *Signer) GetPubkey() *PublicKey {
	if m != nil {
		return m.Pubkey
	}
	return nil
}

func (m *Signer) GetSignature() string {
	if m != nil {
		return m.Signature
	}
	return ""
}

type PrivateKey struct {
	Pubkey       *PublicKey `protobuf:"bytes,1,opt,name=pubkey" json:"pubkey,omitempty"`
	Signature    []byte     `protobuf:"bytes,2,opt,name=signature,proto3" json:"signature,omitempty"`
	Privkey      []byte     `protobuf:"bytes,3,opt,name=privkey,proto3" json:"privkey,omitempty"`
	CryptoSigner *Signer    `protobuf:"bytes,4,opt,name=cryptoSigner" json:"cryptoSigner,omitempty"`
	SigAlgorithm string     `protobuf:"bytes,5,opt,name=sigAlgorithm" json:"sigAlgorithm,omitempty"`
}

func (m *PrivateKey) Reset()                    { *m = PrivateKey{} }
func (m *PrivateKey) String() string            { return proto.CompactTextString(m) }
func (*PrivateKey) ProtoMessage()               {}
func (*PrivateKey) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{42} }

func (m *PrivateKey) GetPubkey() *PublicKey {
	if m != nil {
		return m.Pubkey
	}
	return nil
}

func (m *PrivateKey) GetSignature() []byte {
	if m != nil {
		return m.Signature
	}
	return nil
}

func (m *PrivateKey) GetPrivkey() []byte {
	if m != nil {
		return m.Privkey
	}
	return nil
}

func (m *PrivateKey) GetCryptoSigner() *Signer {
	if m != nil {
		return m.CryptoSigner
	}
	return nil
}

func (m *PrivateKey) GetSigAlgorithm() string {
	if m != nil {
		return m.SigAlgorithm
	}
	return ""
}

type CryptoServiceAddKeyMessage struct {
	RoleName string      `protobuf:"bytes,1,opt,name=roleName" json:"roleName,omitempty"`
	Gun      string      `protobuf:"bytes,2,opt,name=gun" json:"gun,omitempty"`
	Key      *PrivateKey `protobuf:"bytes,3,opt,name=key" json:"key,omitempty"`
}

func (m *CryptoServiceAddKeyMessage) Reset()                    { *m = CryptoServiceAddKeyMessage{} }
func (m *CryptoServiceAddKeyMessage) String() string            { return proto.CompactTextString(m) }
func (*CryptoServiceAddKeyMessage) ProtoMessage()               {}
func (*CryptoServiceAddKeyMessage) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{43} }

func (m *CryptoServiceAddKeyMessage) GetRoleName() string {
	if m != nil {
		return m.RoleName
	}
	return ""
}

func (m *CryptoServiceAddKeyMessage) GetGun() string {
	if m != nil {
		return m.Gun
	}
	return ""
}

func (m *CryptoServiceAddKeyMessage) GetKey() *PrivateKey {
	if m != nil {
		return m.Key
	}
	return nil
}

type PrivateKeyResponse struct {
	Role    string      `protobuf:"bytes,1,opt,name=role" json:"role,omitempty"`
	Gun     string      `protobuf:"bytes,2,opt,name=gun" json:"gun,omitempty"`
	Privkey *PrivateKey `protobuf:"bytes,3,opt,name=privkey" json:"privkey,omitempty"`
	Success bool        `protobuf:"varint,4,opt,name=success" json:"success,omitempty"`
	Message string      `protobuf:"bytes,5,opt,name=message" json:"message,omitempty"`
}

func (m *PrivateKeyResponse) Reset()                    { *m = PrivateKeyResponse{} }
func (m *PrivateKeyResponse) String() string            { return proto.CompactTextString(m) }
func (*PrivateKeyResponse) ProtoMessage()               {}
func (*PrivateKeyResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{44} }

func (m *PrivateKeyResponse) GetRole() string {
	if m != nil {
		return m.Role
	}
	return ""
}

func (m *PrivateKeyResponse) GetGun() string {
	if m != nil {
		return m.Gun
	}
	return ""
}

func (m *PrivateKeyResponse) GetPrivkey() *PrivateKey {
	if m != nil {
		return m.Privkey
	}
	return nil
}

func (m *PrivateKeyResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *PrivateKeyResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type KeyIDMessage struct {
	KeyID string `protobuf:"bytes,1,opt,name=keyID" json:"keyID,omitempty"`
	Gun   string `protobuf:"bytes,2,opt,name=gun" json:"gun,omitempty"`
}

func (m *KeyIDMessage) Reset()                    { *m = KeyIDMessage{} }
func (m *KeyIDMessage) String() string            { return proto.CompactTextString(m) }
func (*KeyIDMessage) ProtoMessage()               {}
func (*KeyIDMessage) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{45} }

func (m *KeyIDMessage) GetKeyID() string {
	if m != nil {
		return m.KeyID
	}
	return ""
}

func (m *KeyIDMessage) GetGun() string {
	if m != nil {
		return m.Gun
	}
	return ""
}

type KeyIDsListResponse struct {
	KeyIDs  []string `protobuf:"bytes,1,rep,name=keyIDs" json:"keyIDs,omitempty"`
	Success bool     `protobuf:"varint,2,opt,name=success" json:"success,omitempty"`
	Message string   `protobuf:"bytes,3,opt,name=message" json:"message,omitempty"`
}

func (m *KeyIDsListResponse) Reset()                    { *m = KeyIDsListResponse{} }
func (m *KeyIDsListResponse) String() string            { return proto.CompactTextString(m) }
func (*KeyIDsListResponse) ProtoMessage()               {}
func (*KeyIDsListResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{46} }

func (m *KeyIDsListResponse) GetKeyIDs() []string {
	if m != nil {
		return m.KeyIDs
	}
	return nil
}

func (m *KeyIDsListResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *KeyIDsListResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type SigningKeyIDsToRolesResponse struct {
	KeyIDs  map[string]string `protobuf:"bytes,1,rep,name=keyIDs" json:"keyIDs,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Success bool              `protobuf:"varint,2,opt,name=success" json:"success,omitempty"`
	Message string            `protobuf:"bytes,3,opt,name=message" json:"message,omitempty"`
}

func (m *SigningKeyIDsToRolesResponse) Reset()                    { *m = SigningKeyIDsToRolesResponse{} }
func (m *SigningKeyIDsToRolesResponse) String() string            { return proto.CompactTextString(m) }
func (*SigningKeyIDsToRolesResponse) ProtoMessage()               {}
func (*SigningKeyIDsToRolesResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{47} }

func (m *SigningKeyIDsToRolesResponse) GetKeyIDs() map[string]string {
	if m != nil {
		return m.KeyIDs
	}
	return nil
}

func (m *SigningKeyIDsToRolesResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *SigningKeyIDsToRolesResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type VersionMessage struct {
	Version int32  `protobuf:"varint,1,opt,name=version" json:"version,omitempty"`
	Gun     string `protobuf:"bytes,2,opt,name=gun" json:"gun,omitempty"`
}

func (m *VersionMessage) Reset()                    { *m = VersionMessage{} }
func (m *VersionMessage) String() string            { return proto.CompactTextString(m) }
func (*VersionMessage) ProtoMessage()               {}
func (*VersionMessage) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{48} }

func (m *VersionMessage) GetVersion() int32 {
	if m != nil {
		return m.Version
	}
	return 0
}

func (m *VersionMessage) GetGun() string {
	if m != nil {
		return m.Gun
	}
	return ""
}

func init() {
	proto.RegisterType((*GunMessage)(nil), "api.GunMessage")
	proto.RegisterType((*AddDelegationMessage)(nil), "api.AddDelegationMessage")
	proto.RegisterType((*AddDelegationRoleAndKeysMessage)(nil), "api.AddDelegationRoleAndKeysMessage")
	proto.RegisterType((*AddDelegationPathsMessage)(nil), "api.AddDelegationPathsMessage")
	proto.RegisterType((*RemoveDelegationKeysAndPathsMessage)(nil), "api.RemoveDelegationKeysAndPathsMessage")
	proto.RegisterType((*RemoveDelegationRoleMessage)(nil), "api.RemoveDelegationRoleMessage")
	proto.RegisterType((*RemoveDelegationPathsMessage)(nil), "api.RemoveDelegationPathsMessage")
	proto.RegisterType((*RemoveDelegationKeysMessage)(nil), "api.RemoveDelegationKeysMessage")
	proto.RegisterType((*RoleNameMessage)(nil), "api.RoleNameMessage")
	proto.RegisterType((*RotateKeyMessage)(nil), "api.RotateKeyMessage")
	proto.RegisterType((*InitMessage)(nil), "api.InitMessage")
	proto.RegisterType((*RoleNameList)(nil), "api.RoleNameList")
	proto.RegisterType((*RoleNameListMessage)(nil), "api.RoleNameListMessage")
	proto.RegisterType((*RoleNameListResponse)(nil), "api.RoleNameListResponse")
	proto.RegisterType((*TargetNameMessage)(nil), "api.TargetNameMessage")
	proto.RegisterType((*Target)(nil), "api.Target")
	proto.RegisterType((*TargetWithRole)(nil), "api.TargetWithRole")
	proto.RegisterType((*TargetWithRoleResponse)(nil), "api.TargetWithRoleResponse")
	proto.RegisterType((*TargetWithRoleNameList)(nil), "api.TargetWithRoleNameList")
	proto.RegisterType((*TargetWithRoleNameListResponse)(nil), "api.TargetWithRoleNameListResponse")
	proto.RegisterType((*TargetByNameAction)(nil), "api.TargetByNameAction")
	proto.RegisterType((*Signature)(nil), "api.Signature")
	proto.RegisterType((*PublicKey)(nil), "api.PublicKey")
	proto.RegisterType((*PublicKeyResponse)(nil), "api.PublicKeyResponse")
	proto.RegisterType((*DelegationRole)(nil), "api.DelegationRole")
	proto.RegisterType((*TargetSigned)(nil), "api.TargetSigned")
	proto.RegisterType((*TargetSignedList)(nil), "api.TargetSignedList")
	proto.RegisterType((*TargetSignedListResponse)(nil), "api.TargetSignedListResponse")
	proto.RegisterType((*BasicResponse)(nil), "api.BasicResponse")
	proto.RegisterType((*Change)(nil), "api.Change")
	proto.RegisterType((*ChangeList)(nil), "api.ChangeList")
	proto.RegisterType((*ChangeListResponse)(nil), "api.ChangeListResponse")
	proto.RegisterType((*RootRole)(nil), "api.RootRole")
	proto.RegisterType((*Role)(nil), "api.Role")
	proto.RegisterType((*RoleList)(nil), "api.RoleList")
	proto.RegisterType((*RoleListResponse)(nil), "api.RoleListResponse")
	proto.RegisterType((*RoleWithSignatures)(nil), "api.RoleWithSignatures")
	proto.RegisterType((*RoleWithSignaturesList)(nil), "api.RoleWithSignaturesList")
	proto.RegisterType((*RoleWithSignaturesListResponse)(nil), "api.RoleWithSignaturesListResponse")
	proto.RegisterType((*CryptoServiceMessage)(nil), "api.CryptoServiceMessage")
	proto.RegisterType((*CryptoServiceCreateMessage)(nil), "api.CryptoServiceCreateMessage")
	proto.RegisterType((*Signer)(nil), "api.Signer")
	proto.RegisterType((*PrivateKey)(nil), "api.PrivateKey")
	proto.RegisterType((*CryptoServiceAddKeyMessage)(nil), "api.CryptoServiceAddKeyMessage")
	proto.RegisterType((*PrivateKeyResponse)(nil), "api.PrivateKeyResponse")
	proto.RegisterType((*KeyIDMessage)(nil), "api.KeyIDMessage")
	proto.RegisterType((*KeyIDsListResponse)(nil), "api.KeyIDsListResponse")
	proto.RegisterType((*SigningKeyIDsToRolesResponse)(nil), "api.SigningKeyIDsToRolesResponse")
	proto.RegisterType((*VersionMessage)(nil), "api.VersionMessage")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Notary service

type NotaryClient interface {
	Initialize(ctx context.Context, in *InitMessage, opts ...grpc.CallOption) (*BasicResponse, error)
	Publish(ctx context.Context, in *GunMessage, opts ...grpc.CallOption) (*BasicResponse, error)
	// AddTarget adds a target to the TUF repository and re-signs.
	AddTarget(ctx context.Context, in *Target, opts ...grpc.CallOption) (*BasicResponse, error)
	// RemoveTarget deletes a target from the TUF repository and re-signs. It only
	// uses the `name` field from the Target object, ignoring all other fields
	RemoveTarget(ctx context.Context, in *Target, opts ...grpc.CallOption) (*BasicResponse, error)
	// ListTargets list the targets for the specified roles in the TUF repository
	ListTargets(ctx context.Context, in *RoleNameListMessage, opts ...grpc.CallOption) (*TargetWithRoleNameListResponse, error)
	// GetTargetByName returns a target by the given name.
	GetTargetByName(ctx context.Context, in *TargetByNameAction, opts ...grpc.CallOption) (*TargetWithRoleResponse, error)
	// GetAllTargetMetadataByName
	GetAllTargetMetadataByName(ctx context.Context, in *TargetNameMessage, opts ...grpc.CallOption) (*TargetSignedListResponse, error)
	// GetChangelist returns the list of the repository's unpublished changes
	GetChangelist(ctx context.Context, in *GunMessage, opts ...grpc.CallOption) (*ChangeListResponse, error)
	ListRoles(ctx context.Context, in *GunMessage, opts ...grpc.CallOption) (*RoleWithSignaturesListResponse, error)
	GetDelegationRoles(ctx context.Context, in *GunMessage, opts ...grpc.CallOption) (*RoleListResponse, error)
	AddDelegation(ctx context.Context, in *AddDelegationMessage, opts ...grpc.CallOption) (*BasicResponse, error)
	AddDelegationRoleAndKeys(ctx context.Context, in *AddDelegationRoleAndKeysMessage, opts ...grpc.CallOption) (*BasicResponse, error)
	AddDelegationPaths(ctx context.Context, in *AddDelegationPathsMessage, opts ...grpc.CallOption) (*BasicResponse, error)
	RemoveDelegationKeysAndPaths(ctx context.Context, in *RemoveDelegationKeysAndPathsMessage, opts ...grpc.CallOption) (*BasicResponse, error)
	RemoveDelegationRole(ctx context.Context, in *RemoveDelegationRoleMessage, opts ...grpc.CallOption) (*BasicResponse, error)
	RemoveDelegationPaths(ctx context.Context, in *RemoveDelegationPathsMessage, opts ...grpc.CallOption) (*BasicResponse, error)
	RemoveDelegationKeys(ctx context.Context, in *RemoveDelegationKeysMessage, opts ...grpc.CallOption) (*BasicResponse, error)
	ClearDelegationPaths(ctx context.Context, in *RoleNameMessage, opts ...grpc.CallOption) (*BasicResponse, error)
	Witness(ctx context.Context, in *RoleNameListMessage, opts ...grpc.CallOption) (*RoleNameListResponse, error)
	RotateKey(ctx context.Context, in *RotateKeyMessage, opts ...grpc.CallOption) (*BasicResponse, error)
	// CryptoService implementation
	CryptoService(ctx context.Context, in *GunMessage, opts ...grpc.CallOption) (*CryptoServiceMessage, error)
	CryptoServiceCreate(ctx context.Context, in *CryptoServiceCreateMessage, opts ...grpc.CallOption) (*PublicKeyResponse, error)
	CryptoServiceAddKey(ctx context.Context, in *CryptoServiceAddKeyMessage, opts ...grpc.CallOption) (*BasicResponse, error)
	CryptoServiceGetKey(ctx context.Context, in *KeyIDMessage, opts ...grpc.CallOption) (*PublicKeyResponse, error)
	CryptoServiceGetPrivateKey(ctx context.Context, in *KeyIDMessage, opts ...grpc.CallOption) (*PrivateKeyResponse, error)
	CryptoServiceRemoveKey(ctx context.Context, in *KeyIDMessage, opts ...grpc.CallOption) (*BasicResponse, error)
	CryptoServiceListKeys(ctx context.Context, in *RoleNameMessage, opts ...grpc.CallOption) (*KeyIDsListResponse, error)
	CryptoServiceListAllKeys(ctx context.Context, in *GunMessage, opts ...grpc.CallOption) (*SigningKeyIDsToRolesResponse, error)
	SetLegacyVersions(ctx context.Context, in *VersionMessage, opts ...grpc.CallOption) (*google_protobuf.Empty, error)
}

type notaryClient struct {
	cc *grpc.ClientConn
}

func NewNotaryClient(cc *grpc.ClientConn) NotaryClient {
	return &notaryClient{cc}
}

func (c *notaryClient) Initialize(ctx context.Context, in *InitMessage, opts ...grpc.CallOption) (*BasicResponse, error) {
	out := new(BasicResponse)
	err := grpc.Invoke(ctx, "/api.Notary/Initialize", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *notaryClient) Publish(ctx context.Context, in *GunMessage, opts ...grpc.CallOption) (*BasicResponse, error) {
	out := new(BasicResponse)
	err := grpc.Invoke(ctx, "/api.Notary/Publish", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *notaryClient) AddTarget(ctx context.Context, in *Target, opts ...grpc.CallOption) (*BasicResponse, error) {
	out := new(BasicResponse)
	err := grpc.Invoke(ctx, "/api.Notary/AddTarget", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *notaryClient) RemoveTarget(ctx context.Context, in *Target, opts ...grpc.CallOption) (*BasicResponse, error) {
	out := new(BasicResponse)
	err := grpc.Invoke(ctx, "/api.Notary/RemoveTarget", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *notaryClient) ListTargets(ctx context.Context, in *RoleNameListMessage, opts ...grpc.CallOption) (*TargetWithRoleNameListResponse, error) {
	out := new(TargetWithRoleNameListResponse)
	err := grpc.Invoke(ctx, "/api.Notary/ListTargets", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *notaryClient) GetTargetByName(ctx context.Context, in *TargetByNameAction, opts ...grpc.CallOption) (*TargetWithRoleResponse, error) {
	out := new(TargetWithRoleResponse)
	err := grpc.Invoke(ctx, "/api.Notary/GetTargetByName", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *notaryClient) GetAllTargetMetadataByName(ctx context.Context, in *TargetNameMessage, opts ...grpc.CallOption) (*TargetSignedListResponse, error) {
	out := new(TargetSignedListResponse)
	err := grpc.Invoke(ctx, "/api.Notary/GetAllTargetMetadataByName", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *notaryClient) GetChangelist(ctx context.Context, in *GunMessage, opts ...grpc.CallOption) (*ChangeListResponse, error) {
	out := new(ChangeListResponse)
	err := grpc.Invoke(ctx, "/api.Notary/GetChangelist", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *notaryClient) ListRoles(ctx context.Context, in *GunMessage, opts ...grpc.CallOption) (*RoleWithSignaturesListResponse, error) {
	out := new(RoleWithSignaturesListResponse)
	err := grpc.Invoke(ctx, "/api.Notary/ListRoles", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *notaryClient) GetDelegationRoles(ctx context.Context, in *GunMessage, opts ...grpc.CallOption) (*RoleListResponse, error) {
	out := new(RoleListResponse)
	err := grpc.Invoke(ctx, "/api.Notary/GetDelegationRoles", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *notaryClient) AddDelegation(ctx context.Context, in *AddDelegationMessage, opts ...grpc.CallOption) (*BasicResponse, error) {
	out := new(BasicResponse)
	err := grpc.Invoke(ctx, "/api.Notary/AddDelegation", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *notaryClient) AddDelegationRoleAndKeys(ctx context.Context, in *AddDelegationRoleAndKeysMessage, opts ...grpc.CallOption) (*BasicResponse, error) {
	out := new(BasicResponse)
	err := grpc.Invoke(ctx, "/api.Notary/AddDelegationRoleAndKeys", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *notaryClient) AddDelegationPaths(ctx context.Context, in *AddDelegationPathsMessage, opts ...grpc.CallOption) (*BasicResponse, error) {
	out := new(BasicResponse)
	err := grpc.Invoke(ctx, "/api.Notary/AddDelegationPaths", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *notaryClient) RemoveDelegationKeysAndPaths(ctx context.Context, in *RemoveDelegationKeysAndPathsMessage, opts ...grpc.CallOption) (*BasicResponse, error) {
	out := new(BasicResponse)
	err := grpc.Invoke(ctx, "/api.Notary/RemoveDelegationKeysAndPaths", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *notaryClient) RemoveDelegationRole(ctx context.Context, in *RemoveDelegationRoleMessage, opts ...grpc.CallOption) (*BasicResponse, error) {
	out := new(BasicResponse)
	err := grpc.Invoke(ctx, "/api.Notary/RemoveDelegationRole", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *notaryClient) RemoveDelegationPaths(ctx context.Context, in *RemoveDelegationPathsMessage, opts ...grpc.CallOption) (*BasicResponse, error) {
	out := new(BasicResponse)
	err := grpc.Invoke(ctx, "/api.Notary/RemoveDelegationPaths", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *notaryClient) RemoveDelegationKeys(ctx context.Context, in *RemoveDelegationKeysMessage, opts ...grpc.CallOption) (*BasicResponse, error) {
	out := new(BasicResponse)
	err := grpc.Invoke(ctx, "/api.Notary/RemoveDelegationKeys", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *notaryClient) ClearDelegationPaths(ctx context.Context, in *RoleNameMessage, opts ...grpc.CallOption) (*BasicResponse, error) {
	out := new(BasicResponse)
	err := grpc.Invoke(ctx, "/api.Notary/ClearDelegationPaths", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *notaryClient) Witness(ctx context.Context, in *RoleNameListMessage, opts ...grpc.CallOption) (*RoleNameListResponse, error) {
	out := new(RoleNameListResponse)
	err := grpc.Invoke(ctx, "/api.Notary/Witness", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *notaryClient) RotateKey(ctx context.Context, in *RotateKeyMessage, opts ...grpc.CallOption) (*BasicResponse, error) {
	out := new(BasicResponse)
	err := grpc.Invoke(ctx, "/api.Notary/RotateKey", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *notaryClient) CryptoService(ctx context.Context, in *GunMessage, opts ...grpc.CallOption) (*CryptoServiceMessage, error) {
	out := new(CryptoServiceMessage)
	err := grpc.Invoke(ctx, "/api.Notary/CryptoService", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *notaryClient) CryptoServiceCreate(ctx context.Context, in *CryptoServiceCreateMessage, opts ...grpc.CallOption) (*PublicKeyResponse, error) {
	out := new(PublicKeyResponse)
	err := grpc.Invoke(ctx, "/api.Notary/CryptoServiceCreate", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *notaryClient) CryptoServiceAddKey(ctx context.Context, in *CryptoServiceAddKeyMessage, opts ...grpc.CallOption) (*BasicResponse, error) {
	out := new(BasicResponse)
	err := grpc.Invoke(ctx, "/api.Notary/CryptoServiceAddKey", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *notaryClient) CryptoServiceGetKey(ctx context.Context, in *KeyIDMessage, opts ...grpc.CallOption) (*PublicKeyResponse, error) {
	out := new(PublicKeyResponse)
	err := grpc.Invoke(ctx, "/api.Notary/CryptoServiceGetKey", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *notaryClient) CryptoServiceGetPrivateKey(ctx context.Context, in *KeyIDMessage, opts ...grpc.CallOption) (*PrivateKeyResponse, error) {
	out := new(PrivateKeyResponse)
	err := grpc.Invoke(ctx, "/api.Notary/CryptoServiceGetPrivateKey", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *notaryClient) CryptoServiceRemoveKey(ctx context.Context, in *KeyIDMessage, opts ...grpc.CallOption) (*BasicResponse, error) {
	out := new(BasicResponse)
	err := grpc.Invoke(ctx, "/api.Notary/CryptoServiceRemoveKey", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *notaryClient) CryptoServiceListKeys(ctx context.Context, in *RoleNameMessage, opts ...grpc.CallOption) (*KeyIDsListResponse, error) {
	out := new(KeyIDsListResponse)
	err := grpc.Invoke(ctx, "/api.Notary/CryptoServiceListKeys", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *notaryClient) CryptoServiceListAllKeys(ctx context.Context, in *GunMessage, opts ...grpc.CallOption) (*SigningKeyIDsToRolesResponse, error) {
	out := new(SigningKeyIDsToRolesResponse)
	err := grpc.Invoke(ctx, "/api.Notary/CryptoServiceListAllKeys", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *notaryClient) SetLegacyVersions(ctx context.Context, in *VersionMessage, opts ...grpc.CallOption) (*google_protobuf.Empty, error) {
	out := new(google_protobuf.Empty)
	err := grpc.Invoke(ctx, "/api.Notary/SetLegacyVersions", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Notary service

type NotaryServer interface {
	Initialize(context.Context, *InitMessage) (*BasicResponse, error)
	Publish(context.Context, *GunMessage) (*BasicResponse, error)
	// AddTarget adds a target to the TUF repository and re-signs.
	AddTarget(context.Context, *Target) (*BasicResponse, error)
	// RemoveTarget deletes a target from the TUF repository and re-signs. It only
	// uses the `name` field from the Target object, ignoring all other fields
	RemoveTarget(context.Context, *Target) (*BasicResponse, error)
	// ListTargets list the targets for the specified roles in the TUF repository
	ListTargets(context.Context, *RoleNameListMessage) (*TargetWithRoleNameListResponse, error)
	// GetTargetByName returns a target by the given name.
	GetTargetByName(context.Context, *TargetByNameAction) (*TargetWithRoleResponse, error)
	// GetAllTargetMetadataByName
	GetAllTargetMetadataByName(context.Context, *TargetNameMessage) (*TargetSignedListResponse, error)
	// GetChangelist returns the list of the repository's unpublished changes
	GetChangelist(context.Context, *GunMessage) (*ChangeListResponse, error)
	ListRoles(context.Context, *GunMessage) (*RoleWithSignaturesListResponse, error)
	GetDelegationRoles(context.Context, *GunMessage) (*RoleListResponse, error)
	AddDelegation(context.Context, *AddDelegationMessage) (*BasicResponse, error)
	AddDelegationRoleAndKeys(context.Context, *AddDelegationRoleAndKeysMessage) (*BasicResponse, error)
	AddDelegationPaths(context.Context, *AddDelegationPathsMessage) (*BasicResponse, error)
	RemoveDelegationKeysAndPaths(context.Context, *RemoveDelegationKeysAndPathsMessage) (*BasicResponse, error)
	RemoveDelegationRole(context.Context, *RemoveDelegationRoleMessage) (*BasicResponse, error)
	RemoveDelegationPaths(context.Context, *RemoveDelegationPathsMessage) (*BasicResponse, error)
	RemoveDelegationKeys(context.Context, *RemoveDelegationKeysMessage) (*BasicResponse, error)
	ClearDelegationPaths(context.Context, *RoleNameMessage) (*BasicResponse, error)
	Witness(context.Context, *RoleNameListMessage) (*RoleNameListResponse, error)
	RotateKey(context.Context, *RotateKeyMessage) (*BasicResponse, error)
	// CryptoService implementation
	CryptoService(context.Context, *GunMessage) (*CryptoServiceMessage, error)
	CryptoServiceCreate(context.Context, *CryptoServiceCreateMessage) (*PublicKeyResponse, error)
	CryptoServiceAddKey(context.Context, *CryptoServiceAddKeyMessage) (*BasicResponse, error)
	CryptoServiceGetKey(context.Context, *KeyIDMessage) (*PublicKeyResponse, error)
	CryptoServiceGetPrivateKey(context.Context, *KeyIDMessage) (*PrivateKeyResponse, error)
	CryptoServiceRemoveKey(context.Context, *KeyIDMessage) (*BasicResponse, error)
	CryptoServiceListKeys(context.Context, *RoleNameMessage) (*KeyIDsListResponse, error)
	CryptoServiceListAllKeys(context.Context, *GunMessage) (*SigningKeyIDsToRolesResponse, error)
	SetLegacyVersions(context.Context, *VersionMessage) (*google_protobuf.Empty, error)
}

func RegisterNotaryServer(s *grpc.Server, srv NotaryServer) {
	s.RegisterService(&_Notary_serviceDesc, srv)
}

func _Notary_Initialize_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InitMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NotaryServer).Initialize(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Notary/Initialize",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NotaryServer).Initialize(ctx, req.(*InitMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _Notary_Publish_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GunMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NotaryServer).Publish(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Notary/Publish",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NotaryServer).Publish(ctx, req.(*GunMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _Notary_AddTarget_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Target)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NotaryServer).AddTarget(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Notary/AddTarget",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NotaryServer).AddTarget(ctx, req.(*Target))
	}
	return interceptor(ctx, in, info, handler)
}

func _Notary_RemoveTarget_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Target)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NotaryServer).RemoveTarget(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Notary/RemoveTarget",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NotaryServer).RemoveTarget(ctx, req.(*Target))
	}
	return interceptor(ctx, in, info, handler)
}

func _Notary_ListTargets_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RoleNameListMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NotaryServer).ListTargets(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Notary/ListTargets",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NotaryServer).ListTargets(ctx, req.(*RoleNameListMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _Notary_GetTargetByName_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TargetByNameAction)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NotaryServer).GetTargetByName(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Notary/GetTargetByName",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NotaryServer).GetTargetByName(ctx, req.(*TargetByNameAction))
	}
	return interceptor(ctx, in, info, handler)
}

func _Notary_GetAllTargetMetadataByName_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TargetNameMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NotaryServer).GetAllTargetMetadataByName(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Notary/GetAllTargetMetadataByName",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NotaryServer).GetAllTargetMetadataByName(ctx, req.(*TargetNameMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _Notary_GetChangelist_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GunMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NotaryServer).GetChangelist(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Notary/GetChangelist",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NotaryServer).GetChangelist(ctx, req.(*GunMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _Notary_ListRoles_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GunMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NotaryServer).ListRoles(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Notary/ListRoles",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NotaryServer).ListRoles(ctx, req.(*GunMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _Notary_GetDelegationRoles_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GunMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NotaryServer).GetDelegationRoles(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Notary/GetDelegationRoles",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NotaryServer).GetDelegationRoles(ctx, req.(*GunMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _Notary_AddDelegation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddDelegationMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NotaryServer).AddDelegation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Notary/AddDelegation",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NotaryServer).AddDelegation(ctx, req.(*AddDelegationMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _Notary_AddDelegationRoleAndKeys_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddDelegationRoleAndKeysMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NotaryServer).AddDelegationRoleAndKeys(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Notary/AddDelegationRoleAndKeys",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NotaryServer).AddDelegationRoleAndKeys(ctx, req.(*AddDelegationRoleAndKeysMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _Notary_AddDelegationPaths_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddDelegationPathsMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NotaryServer).AddDelegationPaths(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Notary/AddDelegationPaths",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NotaryServer).AddDelegationPaths(ctx, req.(*AddDelegationPathsMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _Notary_RemoveDelegationKeysAndPaths_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveDelegationKeysAndPathsMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NotaryServer).RemoveDelegationKeysAndPaths(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Notary/RemoveDelegationKeysAndPaths",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NotaryServer).RemoveDelegationKeysAndPaths(ctx, req.(*RemoveDelegationKeysAndPathsMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _Notary_RemoveDelegationRole_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveDelegationRoleMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NotaryServer).RemoveDelegationRole(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Notary/RemoveDelegationRole",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NotaryServer).RemoveDelegationRole(ctx, req.(*RemoveDelegationRoleMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _Notary_RemoveDelegationPaths_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveDelegationPathsMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NotaryServer).RemoveDelegationPaths(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Notary/RemoveDelegationPaths",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NotaryServer).RemoveDelegationPaths(ctx, req.(*RemoveDelegationPathsMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _Notary_RemoveDelegationKeys_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveDelegationKeysMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NotaryServer).RemoveDelegationKeys(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Notary/RemoveDelegationKeys",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NotaryServer).RemoveDelegationKeys(ctx, req.(*RemoveDelegationKeysMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _Notary_ClearDelegationPaths_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RoleNameMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NotaryServer).ClearDelegationPaths(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Notary/ClearDelegationPaths",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NotaryServer).ClearDelegationPaths(ctx, req.(*RoleNameMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _Notary_Witness_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RoleNameListMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NotaryServer).Witness(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Notary/Witness",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NotaryServer).Witness(ctx, req.(*RoleNameListMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _Notary_RotateKey_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RotateKeyMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NotaryServer).RotateKey(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Notary/RotateKey",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NotaryServer).RotateKey(ctx, req.(*RotateKeyMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _Notary_CryptoService_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GunMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NotaryServer).CryptoService(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Notary/CryptoService",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NotaryServer).CryptoService(ctx, req.(*GunMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _Notary_CryptoServiceCreate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CryptoServiceCreateMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NotaryServer).CryptoServiceCreate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Notary/CryptoServiceCreate",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NotaryServer).CryptoServiceCreate(ctx, req.(*CryptoServiceCreateMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _Notary_CryptoServiceAddKey_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CryptoServiceAddKeyMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NotaryServer).CryptoServiceAddKey(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Notary/CryptoServiceAddKey",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NotaryServer).CryptoServiceAddKey(ctx, req.(*CryptoServiceAddKeyMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _Notary_CryptoServiceGetKey_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(KeyIDMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NotaryServer).CryptoServiceGetKey(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Notary/CryptoServiceGetKey",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NotaryServer).CryptoServiceGetKey(ctx, req.(*KeyIDMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _Notary_CryptoServiceGetPrivateKey_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(KeyIDMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NotaryServer).CryptoServiceGetPrivateKey(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Notary/CryptoServiceGetPrivateKey",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NotaryServer).CryptoServiceGetPrivateKey(ctx, req.(*KeyIDMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _Notary_CryptoServiceRemoveKey_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(KeyIDMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NotaryServer).CryptoServiceRemoveKey(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Notary/CryptoServiceRemoveKey",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NotaryServer).CryptoServiceRemoveKey(ctx, req.(*KeyIDMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _Notary_CryptoServiceListKeys_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RoleNameMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NotaryServer).CryptoServiceListKeys(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Notary/CryptoServiceListKeys",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NotaryServer).CryptoServiceListKeys(ctx, req.(*RoleNameMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _Notary_CryptoServiceListAllKeys_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GunMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NotaryServer).CryptoServiceListAllKeys(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Notary/CryptoServiceListAllKeys",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NotaryServer).CryptoServiceListAllKeys(ctx, req.(*GunMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _Notary_SetLegacyVersions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VersionMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NotaryServer).SetLegacyVersions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Notary/SetLegacyVersions",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NotaryServer).SetLegacyVersions(ctx, req.(*VersionMessage))
	}
	return interceptor(ctx, in, info, handler)
}

var _Notary_serviceDesc = grpc.ServiceDesc{
	ServiceName: "api.Notary",
	HandlerType: (*NotaryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Initialize",
			Handler:    _Notary_Initialize_Handler,
		},
		{
			MethodName: "Publish",
			Handler:    _Notary_Publish_Handler,
		},
		{
			MethodName: "AddTarget",
			Handler:    _Notary_AddTarget_Handler,
		},
		{
			MethodName: "RemoveTarget",
			Handler:    _Notary_RemoveTarget_Handler,
		},
		{
			MethodName: "ListTargets",
			Handler:    _Notary_ListTargets_Handler,
		},
		{
			MethodName: "GetTargetByName",
			Handler:    _Notary_GetTargetByName_Handler,
		},
		{
			MethodName: "GetAllTargetMetadataByName",
			Handler:    _Notary_GetAllTargetMetadataByName_Handler,
		},
		{
			MethodName: "GetChangelist",
			Handler:    _Notary_GetChangelist_Handler,
		},
		{
			MethodName: "ListRoles",
			Handler:    _Notary_ListRoles_Handler,
		},
		{
			MethodName: "GetDelegationRoles",
			Handler:    _Notary_GetDelegationRoles_Handler,
		},
		{
			MethodName: "AddDelegation",
			Handler:    _Notary_AddDelegation_Handler,
		},
		{
			MethodName: "AddDelegationRoleAndKeys",
			Handler:    _Notary_AddDelegationRoleAndKeys_Handler,
		},
		{
			MethodName: "AddDelegationPaths",
			Handler:    _Notary_AddDelegationPaths_Handler,
		},
		{
			MethodName: "RemoveDelegationKeysAndPaths",
			Handler:    _Notary_RemoveDelegationKeysAndPaths_Handler,
		},
		{
			MethodName: "RemoveDelegationRole",
			Handler:    _Notary_RemoveDelegationRole_Handler,
		},
		{
			MethodName: "RemoveDelegationPaths",
			Handler:    _Notary_RemoveDelegationPaths_Handler,
		},
		{
			MethodName: "RemoveDelegationKeys",
			Handler:    _Notary_RemoveDelegationKeys_Handler,
		},
		{
			MethodName: "ClearDelegationPaths",
			Handler:    _Notary_ClearDelegationPaths_Handler,
		},
		{
			MethodName: "Witness",
			Handler:    _Notary_Witness_Handler,
		},
		{
			MethodName: "RotateKey",
			Handler:    _Notary_RotateKey_Handler,
		},
		{
			MethodName: "CryptoService",
			Handler:    _Notary_CryptoService_Handler,
		},
		{
			MethodName: "CryptoServiceCreate",
			Handler:    _Notary_CryptoServiceCreate_Handler,
		},
		{
			MethodName: "CryptoServiceAddKey",
			Handler:    _Notary_CryptoServiceAddKey_Handler,
		},
		{
			MethodName: "CryptoServiceGetKey",
			Handler:    _Notary_CryptoServiceGetKey_Handler,
		},
		{
			MethodName: "CryptoServiceGetPrivateKey",
			Handler:    _Notary_CryptoServiceGetPrivateKey_Handler,
		},
		{
			MethodName: "CryptoServiceRemoveKey",
			Handler:    _Notary_CryptoServiceRemoveKey_Handler,
		},
		{
			MethodName: "CryptoServiceListKeys",
			Handler:    _Notary_CryptoServiceListKeys_Handler,
		},
		{
			MethodName: "CryptoServiceListAllKeys",
			Handler:    _Notary_CryptoServiceListAllKeys_Handler,
		},
		{
			MethodName: "SetLegacyVersions",
			Handler:    _Notary_SetLegacyVersions_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api.proto",
}

func init() { proto.RegisterFile("api.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 1943 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xb4, 0x59, 0x5f, 0x73, 0xdb, 0xc6,
	0x11, 0x0f, 0x48, 0x89, 0x32, 0x97, 0x94, 0x2c, 0x9d, 0x65, 0x8a, 0xa6, 0x6d, 0x59, 0x86, 0xdd,
	0x46, 0x69, 0x26, 0x54, 0xa3, 0xb4, 0x69, 0xd2, 0x34, 0xad, 0x69, 0xda, 0xc3, 0x28, 0xb2, 0x35,
	0x2a, 0x94, 0xd8, 0x33, 0xcd, 0x4c, 0xa7, 0x30, 0x71, 0x25, 0x31, 0x02, 0x01, 0x06, 0x38, 0x69,
	0x8a, 0x3e, 0xb4, 0xd3, 0xbe, 0xb5, 0xd3, 0x99, 0x4e, 0x1e, 0xfb, 0x11, 0xfa, 0xda, 0x6f, 0xd0,
	0xef, 0xe0, 0x0f, 0xd4, 0xb9, 0x3f, 0x38, 0xdc, 0x01, 0x07, 0x4a, 0xe5, 0xb4, 0x6f, 0xbc, 0xc3,
	0xee, 0x6f, 0xff, 0xdc, 0xee, 0xed, 0xde, 0x12, 0x9a, 0xee, 0xdc, 0xef, 0xcf, 0xe3, 0x88, 0x44,
	0xa8, 0xee, 0xce, 0xfd, 0xde, 0xdd, 0x49, 0x14, 0x4d, 0x02, 0x7c, 0xc0, 0xb6, 0xde, 0x5c, 0xfc,
	0xf6, 0xe0, 0xf9, 0x6c, 0x4e, 0x52, 0x4e, 0x61, 0xef, 0x02, 0x8c, 0x2e, 0xc2, 0x97, 0x38, 0x49,
	0xdc, 0x09, 0x46, 0x9b, 0x50, 0x9f, 0x5c, 0x84, 0x5d, 0x6b, 0xcf, 0xda, 0x6f, 0x3a, 0xf4, 0xa7,
	0xfd, 0x57, 0x0b, 0xb6, 0x07, 0x9e, 0xf7, 0x0c, 0x07, 0x78, 0xe2, 0x12, 0x3f, 0x92, 0xa4, 0x08,
	0x56, 0x42, 0x77, 0x86, 0x05, 0x2d, 0xfb, 0x8d, 0x3e, 0x86, 0x0d, 0x4f, 0x12, 0x1e, 0xe3, 0x34,
	0xe9, 0xd6, 0xf6, 0xea, 0xfb, 0xad, 0xc3, 0x8d, 0x3e, 0x55, 0xe9, 0xf4, 0xe2, 0x4d, 0xe0, 0x8f,
	0x8f, 0x71, 0xea, 0x14, 0xa8, 0xd0, 0x36, 0xac, 0xce, 0x5d, 0x32, 0x4d, 0xba, 0xf5, 0xbd, 0xfa,
	0x7e, 0xd3, 0xe1, 0x8b, 0x4c, 0x99, 0x95, 0x5c, 0x99, 0x3f, 0xc2, 0x03, 0x4d, 0x17, 0x27, 0x0a,
	0xf0, 0x20, 0xf4, 0x28, 0xc6, 0xff, 0x43, 0x2d, 0xa1, 0x40, 0x3d, 0x57, 0xe0, 0x35, 0xdc, 0xd1,
	0x14, 0x38, 0xa5, 0x8a, 0x2e, 0x12, 0x2d, 0x2d, 0xab, 0x19, 0x2c, 0x53, 0x80, 0x53, 0x78, 0xe4,
	0xe0, 0x59, 0x74, 0x89, 0x9f, 0x69, 0x2a, 0x0c, 0x42, 0xef, 0x4a, 0x11, 0x1d, 0x68, 0x9c, 0xe3,
	0xf4, 0xe8, 0x59, 0x26, 0x43, 0xac, 0xae, 0xed, 0xd4, 0x21, 0xdc, 0x2d, 0x8a, 0xa6, 0x7e, 0x5d,
	0x24, 0x52, 0x80, 0xd4, 0x72, 0x90, 0x5f, 0xc1, 0xbd, 0x22, 0xc8, 0xff, 0xcc, 0x37, 0xdf, 0x94,
	0x15, 0xbc, 0xea, 0xc4, 0xab, 0x7c, 0x52, 0x06, 0xff, 0x09, 0xdc, 0xa4, 0xd6, 0x9e, 0xb8, 0x33,
	0xd5, 0xe2, 0x38, 0x0a, 0x24, 0x20, 0xfd, 0x6d, 0xb0, 0xf8, 0x0f, 0xb0, 0xe9, 0x44, 0xc4, 0x25,
	0xf8, 0x18, 0xa7, 0x8b, 0x38, 0x7f, 0x00, 0x9b, 0x09, 0x8e, 0x2f, 0x71, 0xfc, 0xd2, 0x0d, 0xdd,
	0x09, 0x4e, 0x8e, 0x71, 0xca, 0x60, 0x6e, 0x38, 0xa5, 0x7d, 0xd4, 0x85, 0xb5, 0x73, 0x9c, 0xbe,
	0xf0, 0x13, 0x22, 0x0e, 0x2d, 0x5b, 0x1a, 0x8e, 0xed, 0xcf, 0x16, 0xb4, 0x8e, 0x42, 0x9f, 0x64,
	0xb2, 0x77, 0x01, 0xe2, 0x28, 0x22, 0xc7, 0xdc, 0x6c, 0x8b, 0xb1, 0x2b, 0x3b, 0x68, 0x00, 0x48,
	0x95, 0xe7, 0x51, 0xab, 0x13, 0xa6, 0x49, 0xeb, 0x70, 0x8b, 0x25, 0x42, 0xe6, 0x07, 0x2a, 0xd0,
	0x31, 0x10, 0x1b, 0xbc, 0xf7, 0x18, 0xda, 0x2a, 0x17, 0x3d, 0xd2, 0x98, 0xe1, 0x72, 0xf9, 0x7c,
	0x61, 0x7f, 0x0e, 0xb7, 0x54, 0xaa, 0x4c, 0x63, 0x23, 0xb1, 0xc1, 0xd3, 0x7f, 0xb2, 0x60, 0x5b,
	0xd3, 0x0d, 0x27, 0xf3, 0x28, 0x4c, 0x30, 0xfa, 0x31, 0xb4, 0x63, 0x65, 0x9f, 0xb9, 0xdd, 0x68,
	0x8c, 0x46, 0x46, 0xbd, 0x9c, 0x5c, 0x8c, 0xc7, 0x38, 0x49, 0xc4, 0x41, 0x64, 0x4b, 0xfa, 0x65,
	0xc6, 0x95, 0x13, 0x46, 0x66, 0x4b, 0xfb, 0x53, 0xd8, 0xfa, 0xca, 0x8d, 0x27, 0x98, 0x14, 0x02,
	0xe5, 0x1a, 0xa9, 0xf1, 0x2f, 0x0b, 0x1a, 0x9c, 0xb7, 0x7c, 0xbd, 0x4a, 0x88, 0x9a, 0x1e, 0xbc,
	0x01, 0x0e, 0x27, 0x64, 0xca, 0x94, 0xa8, 0x3b, 0x62, 0x85, 0x0e, 0xa0, 0x31, 0x75, 0x93, 0x29,
	0x4e, 0xba, 0x2b, 0xec, 0xfa, 0xda, 0x61, 0x86, 0x72, 0xe8, 0xfe, 0x17, 0xec, 0xcb, 0xf3, 0x90,
	0xc4, 0xa9, 0x23, 0xc8, 0x7a, 0x9f, 0x42, 0x4b, 0xd9, 0xa6, 0xd2, 0xcf, 0x71, 0x9a, 0x49, 0x3f,
	0xc7, 0x29, 0x3d, 0x81, 0x4b, 0x37, 0xb8, 0xe0, 0xe2, 0xdb, 0x0e, 0x5f, 0xfc, 0xb4, 0xf6, 0x89,
	0x65, 0x1f, 0xc1, 0x06, 0x07, 0x7e, 0xed, 0x93, 0x29, 0xf5, 0x25, 0x7a, 0x04, 0x0d, 0xc2, 0x76,
	0x84, 0x9b, 0x5b, 0x8a, 0x74, 0x47, 0x7c, 0x92, 0x09, 0x50, 0xcb, 0x13, 0xc0, 0xfe, 0x8b, 0x05,
	0x1d, 0x1d, 0x4b, 0x1e, 0xe0, 0x67, 0xb0, 0x41, 0xb4, 0x2f, 0x02, 0xfb, 0x96, 0x82, 0x2d, 0x99,
	0x0a, 0xa4, 0x4b, 0x1d, 0xe3, 0xa8, 0xa8, 0x8a, 0x0c, 0x8a, 0x0f, 0x60, 0x8d, 0xe3, 0xf3, 0x70,
	0xac, 0xd0, 0x21, 0xa3, 0xb1, 0xff, 0x6e, 0xc1, 0xae, 0x19, 0x49, 0x1a, 0x77, 0x06, 0x1d, 0x62,
	0xa4, 0x10, 0x46, 0xde, 0x35, 0x08, 0x90, 0x20, 0x15, 0xac, 0xd5, 0x46, 0xdb, 0x63, 0x40, 0x1c,
	0xeb, 0x69, 0x4a, 0xa9, 0x07, 0x63, 0x7a, 0x4f, 0x1a, 0x43, 0xf4, 0xdd, 0x2c, 0xef, 0x2a, 0x93,
	0x5f, 0x4f, 0x45, 0x25, 0xdf, 0xbf, 0x85, 0xe6, 0x99, 0x3f, 0x09, 0x5d, 0x72, 0x11, 0xb3, 0xfc,
	0x65, 0xd7, 0xaa, 0x00, 0xe7, 0x0b, 0x1a, 0xbd, 0x33, 0x4c, 0xa6, 0x91, 0x27, 0x82, 0x40, 0xac,
	0xd0, 0x3d, 0x68, 0x26, 0x19, 0x2b, 0x83, 0x6c, 0x3b, 0xf9, 0x06, 0xb5, 0xcb, 0x4f, 0x5e, 0xb9,
	0x81, 0xef, 0xb1, 0x3b, 0xee, 0x86, 0x93, 0x2d, 0xed, 0x5f, 0x42, 0x53, 0x56, 0x68, 0xb4, 0x01,
	0x35, 0xdf, 0x13, 0xf2, 0x6a, 0x3e, 0x03, 0x75, 0x83, 0x49, 0x14, 0xfb, 0x64, 0x3a, 0x13, 0xf2,
	0xf2, 0x0d, 0xaa, 0xca, 0x9c, 0xb1, 0x0a, 0x79, 0x62, 0x65, 0x7f, 0x0d, 0x5b, 0x79, 0xd1, 0xcf,
	0x8e, 0xeb, 0xfb, 0x8c, 0x38, 0x4b, 0x90, 0x72, 0x73, 0x20, 0xbe, 0x2e, 0x38, 0x81, 0xb7, 0x16,
	0x6c, 0xe8, 0x35, 0x14, 0x7d, 0x08, 0x2b, 0xe7, 0xb4, 0xdf, 0xe0, 0x21, 0x75, 0x9f, 0x41, 0xea,
	0x24, 0x7d, 0x5a, 0xca, 0x78, 0xda, 0x32, 0x52, 0xe3, 0x8d, 0x70, 0x0f, 0x9a, 0x64, 0x1a, 0xe3,
	0x64, 0x1a, 0x05, 0x1e, 0xb3, 0x65, 0xd5, 0xc9, 0x37, 0xf2, 0x3a, 0xba, 0xa2, 0xd4, 0xd1, 0xde,
	0x08, 0x9a, 0x12, 0xda, 0x90, 0xfa, 0x8f, 0xd5, 0xd4, 0x2f, 0x5b, 0xab, 0x5c, 0x05, 0x7f, 0xb3,
	0xa0, 0xcd, 0x23, 0x8b, 0x1e, 0x3d, 0xf6, 0xd0, 0xbb, 0x4a, 0x95, 0xcb, 0xf2, 0x44, 0x37, 0x4a,
	0x94, 0xbe, 0xfc, 0xca, 0xa8, 0x55, 0x5f, 0x19, 0x7d, 0x00, 0x19, 0x06, 0xbc, 0x57, 0xc9, 0xb4,
	0x91, 0x91, 0xe6, 0x28, 0x14, 0xf6, 0x2f, 0x60, 0x53, 0xd5, 0x86, 0x65, 0xc5, 0xfb, 0xc5, 0xe4,
	0xdd, 0x52, 0x24, 0x71, 0xba, 0x3c, 0x75, 0xbf, 0xb3, 0xa0, 0x5b, 0x44, 0x90, 0x51, 0x30, 0x80,
	0x4d, 0x52, 0xf8, 0x26, 0xec, 0xbc, 0x5d, 0x82, 0x64, 0x8c, 0x25, 0xf2, 0xa5, 0xee, 0xa5, 0x21,
	0xac, 0x3f, 0x75, 0x13, 0x7f, 0x2c, 0xf5, 0x50, 0x40, 0xac, 0x4a, 0x90, 0x9a, 0x0e, 0xf2, 0x3b,
	0x68, 0x0c, 0xa7, 0x6e, 0x38, 0x61, 0x15, 0xc4, 0x65, 0xf9, 0x2f, 0x4e, 0x5c, 0xac, 0x68, 0xa4,
	0x24, 0xe3, 0x68, 0x9e, 0x71, 0xf2, 0x05, 0x8d, 0x38, 0x92, 0xce, 0x33, 0x9d, 0xd8, 0x6f, 0xba,
	0x47, 0xc3, 0x48, 0x34, 0x1c, 0xec, 0x37, 0x95, 0x3c, 0x8e, 0x42, 0x82, 0x43, 0xd2, 0x5d, 0x65,
	0xf9, 0x94, 0x2d, 0xed, 0x8f, 0x00, 0xb8, 0x64, 0xe6, 0x80, 0xef, 0xc1, 0xda, 0x98, 0xad, 0xb2,
	0xd3, 0xe0, 0xe7, 0xce, 0x29, 0x9c, 0xec, 0x9b, 0x9d, 0x02, 0xca, 0x99, 0xa4, 0xe1, 0x07, 0x00,
	0x9c, 0x20, 0xc8, 0x5d, 0x7f, 0x53, 0xe1, 0x67, 0xc4, 0x0a, 0xc9, 0x52, 0xee, 0x7e, 0x02, 0x37,
	0x9c, 0x28, 0x22, 0x2c, 0x45, 0xf3, 0x56, 0xd1, 0xd2, 0x5a, 0x45, 0x2d, 0xe7, 0x6a, 0x85, 0x9c,
	0xb3, 0xbf, 0x81, 0x15, 0xc6, 0xfd, 0x1e, 0xdc, 0x88, 0x05, 0x92, 0x50, 0x76, 0x5d, 0x5c, 0xa7,
	0x7c, 0xd3, 0x91, 0x9f, 0x8d, 0x89, 0x6d, 0xec, 0xd1, 0xed, 0xf7, 0xa9, 0x7a, 0x01, 0x77, 0xe6,
	0x03, 0xb5, 0x49, 0x6a, 0x1d, 0x36, 0xe5, 0x65, 0x9d, 0x35, 0x57, 0xdf, 0xd2, 0x3e, 0x34, 0xd0,
	0x9d, 0xc8, 0xb4, 0x0a, 0xd4, 0x62, 0xb3, 0x2e, 0xf9, 0x18, 0xa1, 0xfc, 0xbc, 0x94, 0xfb, 0xc6,
	0x80, 0x28, 0x12, 0x2d, 0x4e, 0x32, 0x47, 0x93, 0x42, 0x22, 0x5b, 0x57, 0x25, 0x32, 0xba, 0xaf,
	0xf4, 0x0a, 0x9a, 0x61, 0xbc, 0x6d, 0x70, 0xa1, 0x53, 0x16, 0xc2, 0x54, 0x1e, 0x01, 0x8a, 0x4b,
	0x5f, 0x84, 0xc0, 0x1d, 0x09, 0xa3, 0x7f, 0x76, 0x0c, 0x2c, 0xf6, 0x3f, 0x2d, 0xd8, 0x35, 0xcb,
	0x50, 0x8b, 0x78, 0x6c, 0xa4, 0xd0, 0x8a, 0x78, 0x05, 0x48, 0x05, 0xeb, 0x52, 0x3e, 0xef, 0xc0,
	0xf6, 0x30, 0x4e, 0xe7, 0x24, 0x3a, 0xc3, 0xf1, 0xa5, 0x3f, 0xce, 0x7a, 0x50, 0x7b, 0x0a, 0x3d,
	0x6d, 0x7f, 0x18, 0x63, 0x97, 0xc8, 0x0e, 0xb5, 0xc7, 0x03, 0xe1, 0x24, 0x6f, 0x01, 0xe4, 0xba,
	0xdc, 0xa9, 0xea, 0xd5, 0xb4, 0x5e, 0xa8, 0xa6, 0xf6, 0x09, 0x34, 0xd8, 0x2d, 0x17, 0x5f, 0xbb,
	0x54, 0x6a, 0x25, 0x5f, 0x54, 0x67, 0xb9, 0x61, 0xff, 0xdb, 0x02, 0x38, 0x8d, 0xfd, 0x4b, 0xfe,
	0x84, 0x5a, 0x1e, 0xb4, 0xd8, 0x47, 0xcc, 0x63, 0xff, 0x92, 0xc2, 0xf0, 0x9a, 0x9f, 0x2d, 0xd1,
	0x01, 0xb4, 0xc7, 0xdc, 0x51, 0xcc, 0x08, 0x76, 0xb3, 0x65, 0x57, 0x13, 0xdf, 0x72, 0x34, 0x02,
	0x64, 0x43, 0x3b, 0xf1, 0x27, 0x03, 0xe9, 0x90, 0x55, 0x66, 0x80, 0xb6, 0x67, 0xcf, 0x0a, 0xde,
	0x1f, 0x78, 0x9e, 0xf2, 0x1c, 0xfc, 0xef, 0xbc, 0xff, 0x90, 0xd7, 0xe8, 0xba, 0x72, 0xe5, 0xe5,
	0xee, 0x61, 0x45, 0xdb, 0xfe, 0x87, 0x05, 0x48, 0xd9, 0xcb, 0x82, 0xf4, 0x5a, 0x0f, 0x56, 0xf4,
	0x9e, 0xee, 0x1a, 0x83, 0x0c, 0xe9, 0x2b, 0x25, 0x40, 0x57, 0x2a, 0x03, 0x74, 0x55, 0x0f, 0xd0,
	0x8f, 0xa1, 0xcd, 0x5e, 0x9a, 0xca, 0xeb, 0xce, 0xd0, 0x1d, 0x96, 0x9f, 0x47, 0xbf, 0x01, 0xc4,
	0x5f, 0xa8, 0x5a, 0xde, 0x55, 0xdd, 0xca, 0xcb, 0xa4, 0xce, 0x5b, 0x0b, 0xee, 0xd1, 0x33, 0xf5,
	0xc3, 0x09, 0x97, 0xf4, 0x55, 0xc4, 0xde, 0xb3, 0x52, 0xd8, 0x73, 0x4d, 0x58, 0xeb, 0xf0, 0x03,
	0x19, 0x14, 0x55, 0x2c, 0x7d, 0xbe, 0x2b, 0x9e, 0x5b, 0xcb, 0xeb, 0x46, 0x9f, 0x68, 0x0a, 0xd4,
	0x55, 0x4f, 0xb4, 0xa6, 0xda, 0x97, 0xfd, 0x0c, 0x36, 0x5e, 0xe1, 0x38, 0x51, 0x46, 0x72, 0x5d,
	0x58, 0xbb, 0xe4, 0x3b, 0x0c, 0x61, 0xd5, 0xc9, 0x96, 0x65, 0xb7, 0x1f, 0x7e, 0xb7, 0x09, 0x8d,
	0x93, 0x88, 0xb8, 0x71, 0x8a, 0x7e, 0x04, 0x70, 0x14, 0xfa, 0xc4, 0x77, 0x03, 0xff, 0xf7, 0x18,
	0x6d, 0x32, 0xe3, 0x95, 0xc9, 0x42, 0x0f, 0xb1, 0x1d, 0xad, 0x3f, 0xb1, 0xdf, 0x41, 0x3f, 0x84,
	0x35, 0x96, 0x9c, 0xc9, 0x14, 0xf1, 0x40, 0xca, 0xc7, 0x88, 0x15, 0x1c, 0x7d, 0x68, 0x0e, 0x3c,
	0x4f, 0x3c, 0x85, 0xd5, 0x5e, 0xb0, 0x82, 0xfe, 0x43, 0x68, 0xf3, 0xb9, 0xcf, 0xf5, 0x59, 0x4e,
	0xa0, 0x45, 0xc3, 0x88, 0xd3, 0x24, 0xa8, 0x5b, 0x7a, 0xda, 0x64, 0x1a, 0x3e, 0x5a, 0xf4, 0xf8,
	0xca, 0xf1, 0x8e, 0xe0, 0xe6, 0x08, 0x13, 0xf5, 0x5d, 0x85, 0xd4, 0x57, 0xb7, 0xfa, 0xd4, 0xea,
	0x99, 0xde, 0x73, 0x0a, 0xd4, 0xd7, 0xd0, 0x1b, 0x61, 0x32, 0x08, 0x02, 0x4e, 0xf1, 0x12, 0x13,
	0xd7, 0x73, 0x89, 0x2b, 0x50, 0x3b, 0x0a, 0xb3, 0x32, 0x62, 0xe8, 0xdd, 0x37, 0x77, 0x9d, 0x39,
	0xec, 0x67, 0xb0, 0x3e, 0xc2, 0x64, 0x98, 0xf7, 0x43, 0xa5, 0xc3, 0xd8, 0x29, 0x76, 0x4f, 0x39,
	0xf3, 0x10, 0x9a, 0x6c, 0x87, 0xbd, 0xf6, 0x4a, 0x8c, 0x8f, 0x16, 0xd5, 0xb6, 0x1c, 0xe4, 0xe7,
	0x80, 0x46, 0x98, 0xe8, 0x0f, 0x00, 0x03, 0xda, 0x6d, 0xbd, 0x03, 0xc9, 0xf9, 0x9f, 0xc0, 0xba,
	0x36, 0x53, 0x45, 0x77, 0x18, 0xa5, 0x69, 0xe8, 0x5c, 0x71, 0xea, 0xaf, 0xa0, 0x5b, 0x35, 0x16,
	0x46, 0x8f, 0xcb, 0x60, 0xe5, 0xa9, 0x71, 0x05, 0xee, 0x97, 0x80, 0xca, 0xd3, 0x5e, 0xb4, 0x5b,
	0x46, 0x54, 0x47, 0x9d, 0x15, 0x58, 0xbf, 0x2e, 0x0f, 0x48, 0xd5, 0x01, 0x2f, 0xda, 0xe7, 0xee,
	0xb9, 0x7a, 0x06, 0x5c, 0x19, 0xf9, 0xdb, 0xa6, 0x29, 0x2e, 0xda, 0x33, 0xe2, 0x2a, 0x03, 0xde,
	0x0a, 0xbc, 0x53, 0xb8, 0x6d, 0x1c, 0xe8, 0xa2, 0x87, 0x46, 0xc0, 0xe5, 0x34, 0x64, 0x27, 0xb4,
	0x57, 0x69, 0xf9, 0x62, 0xbc, 0xa7, 0xb0, 0x3d, 0x0c, 0xb0, 0x1b, 0x17, 0x15, 0xdc, 0xd6, 0x92,
	0x7e, 0x31, 0xc6, 0x13, 0x58, 0x7b, 0xed, 0x93, 0x90, 0xdd, 0xd1, 0x95, 0x77, 0xc5, 0x9d, 0xf2,
	0x80, 0x24, 0x47, 0xf8, 0x04, 0x9a, 0x72, 0x0c, 0x8c, 0xb2, 0x18, 0xd7, 0xc7, 0xc2, 0x15, 0xb2,
	0x3f, 0x87, 0x75, 0xad, 0x77, 0x28, 0xa7, 0x0c, 0x17, 0x6c, 0x6c, 0xfb, 0xe8, 0x01, 0xdd, 0x32,
	0x34, 0x7e, 0xe8, 0x41, 0x99, 0x47, 0x6b, 0x09, 0x7b, 0x9d, 0x42, 0x5f, 0x95, 0x2b, 0xf4, 0xa2,
	0x80, 0xc8, 0x9b, 0x19, 0x13, 0xa2, 0xd6, 0xe6, 0x54, 0x1e, 0x8f, 0x8e, 0x36, 0xc2, 0x84, 0xa2,
	0xf1, 0x97, 0xb9, 0xda, 0x29, 0x2c, 0xd0, 0xe8, 0xcb, 0x42, 0x7b, 0x35, 0xc2, 0x44, 0xe9, 0x18,
	0x0d, 0x50, 0x3b, 0xc5, 0x96, 0x26, 0xc7, 0x1a, 0x40, 0x47, 0xc3, 0xe2, 0x01, 0x57, 0x81, 0x63,
	0x36, 0xe9, 0x0b, 0xb8, 0xad, 0x41, 0xd0, 0x50, 0xe0, 0xff, 0x5f, 0x19, 0x43, 0x6e, 0x27, 0xc7,
	0x2d, 0xde, 0x99, 0xa7, 0xd0, 0x2d, 0x21, 0x0d, 0x82, 0x80, 0x81, 0x95, 0xc2, 0xe0, 0xe1, 0x95,
	0xed, 0x08, 0x73, 0xf7, 0xd6, 0x19, 0x26, 0x2f, 0xf0, 0xc4, 0x1d, 0xa7, 0xa2, 0x2d, 0x48, 0x10,
	0x9f, 0xcd, 0xe8, 0x5d, 0x42, 0xaf, 0xd3, 0xe7, 0xff, 0x07, 0xf6, 0xb3, 0xff, 0x03, 0xfb, 0xec,
	0xff, 0x40, 0xfb, 0x9d, 0x37, 0x0d, 0xb6, 0xf3, 0xd1, 0x7f, 0x02, 0x00, 0x00, 0xff, 0xff, 0x7b,
	0xf1, 0xa4, 0xe4, 0x41, 0x1c, 0x00, 0x00,
}
